version: '3'
services:
  db:
    build:
      context: ./docker_conf/
      dockerfile: Dockerfile.postgres
    container_name: db1
    volumes:
      - postgresql:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./docker_conf/Dockerfile.app
    command: "rails server --port 3000 --binding=0.0.0.0"
    depends_on:
      - db
    container_name: app1
    volumes:
      - ./:/ruby_test
    environment:
      DATABASE_URL: postgres://postgres@db
    expose:
      - "3000"
    ports:
      - "3000:3000"
volumes:
  postgresql:

